---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _includes/bandeau.md
  label: Bandeau
- type: document
  path: index.markdown
  label: Accueil
- type: directory
  path: _category
  label: Onglets
  create: documents
  match: "**/*"
  templates:
  - 01_nouvel-onglet
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - 02-nouvelle-expo
  - 02-nouvelle-ressource
  - 02-nouveau-qui-sommes-nous
  - 02-nouveau-nous-soutenir
  - nouvel-le-artiste
upload_dir: imgs
public_path: "/imgs"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
